Design, data and dev blog post
dddsydney/dddsydney-blog pull request #1
Opened 2018-04-21 05:08 UTC by stephengodbold

2018-04-22 03:42 UTC, aaronpowell requested changes

2018-04-22 03:42 UTC, aaronpowell commented on src/content/posts/design-dev-data.md
> +Back in 2011, HP ditched it's flagging computer business to focus on software. Then member of the board Marc Andreesson and co-founder of famed tech investment firm Andreesson-Horowitz reasoned in an
You need a header, check out the other posts.

2018-04-23 11:02 UTC, stephengodbold commented
Changes made. Process please 😀

2018-04-23 11:09 UTC, aaronpowell approved these changes

2018-04-23 11:09 UTC, merged